name: VirtualCrates
version: 1.3.0
depend: [CrateReloaded]
loadafter: [PlaceholderAPI, Citizens]
softdepend: [PlaceholderAPI, Citizens]
main: com.virtualcrates.VirtualCrates
commands:
  virtualcrates:
    aliases: ["vcrate", "vcrates"]
  convert: